# Generated by Django 6.1.1 on 2026-09-22 00:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('term_unit', models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LOAN', 'On loan'), ('MAINTENANCE', 'In maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=12)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('acquired_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('institutional_email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('OPERATOR', 'Desk operator')], default='OPERATOR', max_length=10)),
                ('is_temporary', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('entity_name', models.CharField(max_length=40)),
                ('entity_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('term_value', models.PositiveSmallIntegerField()),
                ('term_unit', models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days')], max_length=5)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=10)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_received', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_given', to=settings.AUTH_USER_MODEL)),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='apiGit.resourceitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='apiGit.student')),
            ],
        ),
        migrations.CreateModel(
            name='LoanReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='SENT', max_length=8)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='apiGit.loan')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_or_brand', models.CharField(blank=True, max_length=120)),
                ('reference_code', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='apiGit.category')),
            ],
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='resource_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='apiGit.resourcetitle'),
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_late', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('rule_applied', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sanction', to='apiGit.loan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to='apiGit.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('resource_item',), name='unique_active_loan_per_item'),
        ),
    ]
